# fly.toml app configuration file generated for stolen-instruments-api on 2024-06-28T09:24:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stolen-instruments-api"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
